"""ADB interface contract used by runner and flow steps."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol


class IAdb(Protocol):
    serial: str

    def connect(self) -> None: ...

    def tap(self, x: int, y: int) -> None: ...

    def keyevent(self, keycode: int) -> None: ...

    def start_app(self, package: str, activity: str) -> None: ...

    def launch_app(self, package: str, activity: str) -> None: ...

    def get_screen_resolution(self) -> tuple[int, int]: ...

    def is_running(self) -> bool: ...

    def launch_instance(self, timeout: int = 120) -> bool: ...

    def list_instances(self) -> list[dict[str, object]]: ...
    def stop_app(self, package: str) -> None: ...

    def input_text(self, text: str) -> None: ...

    def open_url(self, url: str) -> None: ...

    def screencap(self, output_path: str) -> Path: ...
